apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
  labels:
    managed-by: {{ .Values.deploymentName }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      application: {{ .Values.application }}
  template:
    metadata:
      labels:
        application: {{ .Values.application }}
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }} #nginx-sa
      containers:
        - name: {{ .Values.containerName}} #nginx
          image: us-central1-docker.pkg.dev/my-project-417822/app-repo/docker-gar:v1
          ports:
            - name: http
              containerPort: 80