apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    managed-by: dso
spec:
  selector:
    application: nginx-app
  ports:
    - name: {{ .Values.nginxApp.portName }}
      port: {{ .Values.nginxApp.portNumber }}
      targetPort: {{ .Values.nginxApp.targetPort }}